version: '3.8'

services:
  postgres:
    container_name: postgres
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: 'redis:latest'
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.0.2-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  postgres_data:
  redis-data: